In [1]:
import numpy as np


In [3]:
a = int(input("Enter no of rows "))
b = int(input("Enter no of cols "))

Enter no of rows 2
Enter no of cols 2


In [4]:
m1 = []

for i in range(0, a):
    t = []
    for j in range(0, b):
        t.append(int(input(" ")))
        
    m1.append(t)
print("Matrix 1", m1)

 3
 4
 5
 2
Matrix 1 [[3, 4], [5, 2]]


In [5]:
m2 = []
for i in range(0, a):
    t = []
    for j in range(0, b):
        t.append(int(input(" ")))
        
    m2.append(t)
print("Matrix 2", m2)


 1
 4
 5
 2
Matrix 2 [[1, 4], [5, 2]]


In [24]:
m3 = np.add(m1, m2)
m4 = np.dot(m1, m2)
m5 = np.subtract(m1, m2)
m6 = np.transpose(m3)

print("Addition\n", m3)
print("Multiplication\n", m4)
print("Substration\n", m5)
print("Transpose\n", m6)

Addition
 [[ 4  8]
 [10  4]]
Multiplication
 [[23 20]
 [15 24]]
Substration
 [[2 0]
 [0 0]]
Transpose
 [[ 4 10]
 [ 8  4]]
